package ru.ruslan.life_expectancy.utils

import ru.ruslan.life_expectancy.Model.Country

class CountriesListCreator {
    companion object {
        fun <ArrayList> getCountriesList(): ArrayList {
            var countriesList = ArrayList<Country>()
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Estonia", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Sweden", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Austria", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            countriesList.add(Country("Russian Federation", "RU", "\uD83C\uDDF7\uD83C\uDDFA"))
            return countriesList as ArrayList
        }
    }
}